[build]
  command = "CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
NODE_VERSION = "18"
REACT_APP_SUPABASE_URL="https://wcinvkunarmkiyihbtow.supabase.co"
REACT_APP_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjaW52a3VuYXJta2l5aWhidG93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjQ3MjksImV4cCI6MjA3MzIwMDcyOX0.yhxCa1nuBxBp3hxFDWoCzZZUbr0luDBmxhSS-ilNsKg"
